OBJS = triangular.cpp /home/projects/opengl/1/includes/src/glad.c
CFLAG = -Wall -g
CC = g++
INCLUDES = -I/home/projects/opengl/1/includes/include -I/home/projects/opengl/1/includes
LIBS = -lglfw -lGL -lglut -lGLEW  -lGL -lX11 -lpthread -lXrandr -lXi -ldl
prog:${OBJ}
	${CC} ${CFLAGS} ${INCLUDES} -o $@ ${OBJS} ${LIBS}
